apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240605220619.0.0+build.6aff574
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240605220619.0.0+build.6aff574
  releaseNotes: |
    Release v20240605220619.0.0+build.6aff574 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-05-06-2024-11-55-55-754911279/where-for-dinner-ui-my-apps-bundle@sha256:dc441b997662d55058c06c16c125ee1f75457add66b6182e11a42bf2ffcc8e43
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

