apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240605220728.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240605220728.0.0+build.6aff574
  releaseNotes: |
    Release v20240605220728.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-05-06-2024-11-55-55-754911279/where-for-dinner-my-apps-bundle@sha256:bd6ad9a77b40f26f893211b95caa93938c305ead584ba5c46ba5f38e62772632
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

