apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240605220730.0.0+build.6aff574
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240605220730.0.0+build.6aff574
  releaseNotes: |
    Release v20240605220730.0.0+build.6aff574 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-05-06-2024-11-55-55-754911279/where-for-dinner-availability-my-apps-bundle@sha256:1d261931e3ba31eb0fe34d2cfdb417ab85547787b86deb8a9418c962c5fd87be
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

